- name: Deploy App to Kubernetes (kind)
  hosts: all
  become: true

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reset ssh connection
      meta: reset_connection

    - name: Install kind
      shell: |
        curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
        chmod +x /usr/local/bin/kind

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl

    - name: Create kind cluster
      shell: kind create cluster --name devops-cluster --wait 90s

    - name: Set up kubeconfig for ubuntu user
      shell: |
        mkdir -p /home/ubuntu/.kube
        kind get kubeconfig --name devops-cluster > /home/ubuntu/.kube/config
        chown -R ubuntu:ubuntu /home/ubuntu/.kube

    - name: Check Nodes
      become_user: ubuntu
      command: kubectl get nodes

    - name: Copy Deployment File
      copy:
        src: ../kubernetes/deployment.yml
        dest: /home/ubuntu/deployment.yml

    - name: Copy Service File
      copy:
        src: ../kubernetes/service.yml
        dest: /home/ubuntu/service.yml

    - name: Apply Deployment
      become_user: ubuntu
      command: kubectl apply -f /home/ubuntu/deployment.yml

    - name: Apply Service
      become_user: ubuntu
      command: kubectl apply -f /home/ubuntu/service.yml

    - name: Update Image
      become_user: ubuntu
      command: kubectl set image deployment/static-website node-container={{ image }}

    - name: Wait for Rollout
      become_user: ubuntu
      command: kubectl rollout status deployment/static-website





 # - name: Download Minikube
    #   get_url:
    #     url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    #     dest: /usr/local/bin/minikube
    #     mode: '0755'

    

    # - name: Install kubectl
    #   snap:
    #     name: kubectl
    #     classic: yes

    

    # - name: Wait for docker
    #   pause:
    #     seconds: 30

    

    # - name: Start Minikube
    #   become_user: ubuntu
    #   shell: minikube start --driver=none
    #   args:
    #     executable: /bin/bash      