- name: Deploy App to Minikube
  hosts: all
  become: true

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install kubectl
      snap:
        name: kubectl
        classic: yes

    - name: Start Minikube (if not running)
      become_user: ubuntu
      command: minikube start --driver=docker
      ignore_errors: yes

    - name: Update Kubernetes Deployment Image
      become_user: ubuntu
      command: kubectl set image deployment/static-website node-container={{ image }}

    - name: Apply Service
      become_user: ubuntu
      command: kubectl apply -f kubernetes/service.yml